application: wilog
version: 1
runtime: python
api_version: 1

handlers: 
- url: /(.*\.(gif|png|jpg|ico))
  static_files: static/\1
  upload: static/(.*\.(gif|png|jpg|ico))

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images
 
- url: /.* 
  script: pb.py
