application: wilog
version: 1
runtime: python
api_version: 1

handlers: 
- url: /(.*\.(gif|png|jpg|ico))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg|ico))

- url: /(.*\.(css))
  static_files: stylesheets/\1
  upload: stylesheets/(.*\.(css))

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images
 
- url: /.* 
  script: pb.py
